"""improve forum

Revision ID: 128be91344af
Revises: 5fe139c46e60
Create Date: 2025-08-04 23:08:08.266521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128be91344af'
down_revision = '5fe139c46e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.drop_column('body')

    # ### end Alembic commands ###
