"""empty message

Revision ID: 3b618ef4319d
Revises: a16fe4963cea
Create Date: 2026-02-08 23:01:09.252477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b618ef4319d'
down_revision = 'a16fe4963cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_activities_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('mentor_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('areas_of_interest', sa.String(length=500), nullable=True))
        batch_op.alter_column('phone_no',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_type')

    with op.batch_alter_table('mentor_applications', schema=None) as batch_op:
        batch_op.alter_column('phone_no',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('areas_of_interest')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_activities_user_id'))

    op.drop_table('user_activities')
    # ### end Alembic commands ###
