name:   Flask API testing

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      TEST_SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
      TEST_DATABASE_URI: ${{ secrets.TEST_DATABASE_URI }}
      FLASK_ENV: ${{ secrets.FLASK_ENV }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      PROD_SECRET_KEY: ${{ secrets.PROD_SECRET_KEY}}
      PROD_DATABASE_URI: ${{ secrets.PROD_DATABASE_URI}}
      API_KEY: ${{ secrets.API_KEY }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest